### ISSUE TITLE
Bug for item 2527

### ISSUE THREAD

**Issue by Camtoe112** [RTRGitHub/RTRRedux#175]
Causes client crash on placement in the world, as well as scrolling over it with cursor.

**Comment by Solidflip** [comment]
Item banned due to crashing the server, will revisit if someone actually needs it

**Comment by Abouttabs** [comment]
Just a followup here, could craahlogs be attached to all issues with crashes? It is immensely helpful because we don't need to recreate the issue ourselves, it saves us time... Also that way we can look at it even on our phones when we are not by our computers and maybe even suggest a solution that can be put into effect by another mod/admin that is there/will be there sooner... Thank you.
