### ISSUE TITLE
AR rank messed up

### ISSUE THREAD

**Issue by altoidsyn** [RTRGitHub/RTRRedux#489]
I noticed that for some reason, I'm Baron rank but I need 5 days of game time to reach Count, even though I had 155 hours on the last server. It thinks I only have 22 hours of game time, which suggests that it got messed up and then didn't get fixed.

**Comment by dragonaslin** [comment]
talk to soup

**Comment by altoidsyn** [comment]
So, I put this on GitHub in the hopes that it would eventually be fixed. Then today, a server crash and subsequent hours wipe put me back at 0 hours again. I wouldn't be complaining, except someone else's hours were fixed within a few hours. At this point, I should be Viscount (I have approximately 175 hours between where last server closed and now), but instead I'm literally going to have to play a week of hours  to get my correct rank and hours.  

It's really frustrating that I was told to put it on GitHub in the first place and then told that I have to wait until someone takes pity on me and fixes it.  I understand not wanting every little issue on here, but I've been waiting for this to be fixed since the last map and watching other players get their issues fixed within 24 hours, while I'm still waiting hurts.  

I really appreciate everything that the administrator and moderator teams do for us on a day to day basis, so posting things like this make me feel like a shitty person. I just want my hours and rank fixed, please.  

Thank you.

**Comment by Camtoe112** [comment]
There are backups in the backend for this very reason. For anyone handling this, just go in the backend and check what his time was before it messed up, and re add it. If its server wide, restore from latest correct backup.

Quickfix : /ar set altoidsyn <X>h
X = (previous hrs + current hrs) h
No ">"s

For altoidsyn: Did you log in at all before the map reset? Have you just recently started playing on this map? It thinks you have 22hrs of gameplay because thats the amount of time youve played on this map before this was noticed. That can be added to current numbers easily.

It was a known issue that if you played on the last map, and the server accidentally wiped the rank times and claims, and did not get it fixed afterwards personalyl by a Mod/Admin, it would carry over to this map incorrectly. 

No reason to take it personally, theres a lot to always fix and do that distracts us. We do this for fun and to help! If you have sufficient rank in RtR you can also assist us in applying to be a Mod.

Thanks!!!
